language: python
python:
    - "2.7"
install: pip install -r requirements.txt
before_script:
  - cp config/database.yml.travis config/database.yml
script:
    - PYTHONPATH=. python tests/test_filters.py
    - PYTHONPATH=. python tests/test_views_integration.py
   